# Generated by Django 5.1.4 on 2025-01-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_repo_scm_type_alter_worker_scm"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="encrypted_lando_api_key",
            field=models.BinaryField(blank=True, default=b""),
        ),
    ]
