# Generated by Django 6.0.5 on 2026-06-10 02:19

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_autoformatchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='upliftjob',
            name='mode',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update')], default='CREATE', max_length=8),
        ),
        migrations.AddField(
            model_name='upliftjob',
            name='parent_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_jobs', to='main.upliftjob'),
        ),
        migrations.AddIndex(
            model_name='upliftsubmission',
            index=django.contrib.postgres.indexes.GinIndex(fields=['requested_revision_ids'], name='main_uplift_request_0b5367_gin'),
        ),
    ]
